version: "3.8"
services:
  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db
    # environment:
    #   - MONGO_INITDB_USERNAME: user
    #   - MONGO_INITDB_PASSWORD: password
  backend:
    build: ./backend
    ports:
      - "80:80"
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules

  # frontend:

volumes:
  data:
  logs:
