version: "3.8"
services:
  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db
    environment:
      - MONGO_INITDB_USERNAME: user
      - MONGO_INITDB_PASSWORD: password
  # backend:
  # frontend:
